# Generated by Django 2.2 on 2020-07-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=300)),
                ('event_image', models.ImageField(blank=True, default='event-default.jpg', null=True, upload_to='event-images')),
                ('event_description', models.TextField(help_text='Enter event description')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PAST', 'Past')], default='UPCOMING', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
