# Generated by Django 2.2 on 2019-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=250)),
                ('sponsor_logo', models.ImageField(default='', upload_to='')),
                ('sponsor_bio', models.TextField()),
                ('sponsor_website_url', models.CharField(max_length=250)),
                ('sponsor_twitter_url', models.CharField(max_length=250)),
            ],
        ),
    ]
