# Generated by Django 2.2 on 2019-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_pics'),
        ),
    ]
