# Generated by Django 2.2 on 2019-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20190726_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_logo',
            field=models.ImageField(default=13, upload_to='sponsor_pics'),
            preserve_default=False,
        ),
    ]
