# Generated by Django 2.2 on 2019-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20190709_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_twitter_url',
            field=models.CharField(blank=True, default='#', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_website_url',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
